application:
  subdomain: srs
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://srs:8080/
    - location: /api/
      backend: http://srs:1985/
  ingress:
    - protocol: tcp
      port: 1935
      service: srs
    - protocol: tcp
      port: 1985
      service: srs
    - protocol: tcp
      port: 1990
      service: srs
    - protocol: tcp
      port: 8080
      service: srs
    - protocol: tcp
      port: 8088
      service: srs
    - protocol: udp
      port: 8000
      service: srs
    - protocol: udp
      port: 10080
      service: srs
services:
  srs:
    # upstream: ossrs/srs:6.0.184
    image: registry.lazycat.cloud/czyt/ossrs/srs:5aaf271551f5fc1c
