lzc-sdk-version: "0.1"
name: SRS
package: cloud.lazycat.app.srs
version: 6.0.0
description: 一个开源的（MIT协议）简单高效的实时视频服务器，支持RTMP、WebRTC、HLS、HTTP-FLV、SRT、MPEG-DASH和GB28181等协议。
homepage: https://ossrs.net/lts/zh-cn/
author: ossrs
application:
  subdomain: srs
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://srs.cloud.lazycat.app.srs.lzcapp:8080/
    - /api/=http://srs.cloud.lazycat.app.srs.lzcapp:1985/
  ingress:
    - protocol: tcp
      port: 1935
      service: srs
      
    - protocol: tcp
      port: 1985
      service: srs

    - protocol: tcp
      port: 1990
      service: srs

    - protocol: tcp
      port: 8080
      service: srs

    - protocol: tcp
      port: 8088
      service: srs

    - protocol: udp
      port: 8000
      service: srs

    - protocol: udp
      port: 10080
      service: srs
services:
  srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:6
